Repository aspida/pathpida, pull requests merged in 2023-07, with the labels that each got.

#178 安定版AppDirへの対応
  projects/nextjs-stable-appdir/.pathpidaignore
  projects/nextjs-stable-appdir/app/%E6%97%A5%E6%9C%AC%E8%AA%9E/page.tsx
  projects/nextjs-stable-appdir/app/(group1)/[pid]/page.tsx
  projects/nextjs-stable-appdir/app/(group1)/blog/[...slug]/page.tsx
  projects/nextjs-stable-appdir/app/(group1)/blog/hoge/[[...fuga]]/page.tsx
  projects/nextjs-stable-appdir/app/(group2)/aaa/[...bbb]/ccc/page.tsx
  projects/nextjs-stable-appdir/app/(group2)/aaa/api/samples/page.ts
  projects/nextjs-stable-appdir/app/(group2)/x/[y]/page.tsx
  projects/nextjs-stable-appdir/app/(group2)/x/[y]/z/page.tsx
  projects/nextjs-stable-appdir/app/(group2)/x/page.tsx
  projects/nextjs-stable-appdir/app/.ignore/page.tsx
  projects/nextjs-stable-appdir/app/[a]/b/[...c]/page.tsx
  projects/nextjs-stable-appdir/app/[a]/b/index.module.css
  projects/nextjs-stable-appdir/app/_app.tsx
  projects/nextjs-stable-appdir/app/index.module.scss
  projects/nextjs-stable-appdir/app/page.tsx
  projects/nextjs-stable-appdir/lib/$path.ts
  projects/nextjs-stable-appdir/next.config.js
  projects/nextjs-stable-appdir/out/lib/basic/$path.ts
  projects/nextjs-stable-appdir/out/lib/ignore/$path.ts
  projects/nextjs-stable-appdir/out/lib/static/$path.ts
  projects/nextjs-stable-appdir/package.json
  projects/nextjs-stable-appdir/pages/children/%E6%97%A5%E6%9C%AC%E8%AA%9E/index.tsx
  projects/nextjs-stable-appdir/pages/children/.ignore/index.tsx
  projects/nextjs-stable-appdir/pages/children/[a]/b/[...c].tsx
  projects/nextjs-stable-appdir/pages/children/[a]/b/index.module.css
  projects/nextjs-stable-appdir/pages/children/[pid].tsx
  projects/nextjs-stable-appdir/pages/children/_app.tsx
  projects/nextjs-stable-appdir/pages/children/aaa/[...bbb]/ccc.tsx
  projects/nextjs-stable-appdir/pages/children/aaa/api/samples.ts
  projects/nextjs-stable-appdir/pages/children/api/users.ts
  projects/nextjs-stable-appdir/pages/children/blog/[...slug].tsx
  projects/nextjs-stable-appdir/pages/children/blog/hoge/[[...fuga]].tsx
  projects/nextjs-stable-appdir/pages/children/index.module.scss
  projects/nextjs-stable-appdir/pages/children/x/[y].tsx
  projects/nextjs-stable-appdir/pages/children/x/[y]/z.tsx
  projects/nextjs-stable-appdir/public/aa.json
  projects/nextjs-stable-appdir/public/bb/.ignore
  projects/nextjs-stable-appdir/public/bb/cc.png
  projects/nextjs-stable-appdir/public/duplicate-json/sample.json
  projects/nextjs-stable-appdir/public/duplicate.json
  projects/nextjs-stable-appdir/public/duplicate_json
  projects/projects.ts
  src/getConfig.ts
Labels: bug

#179 Provide dynamic route path for Next.js app directory
  projects/nextjs-appdir/lib/$path.ts
  projects/nextjs-appdir/out/lib/basic/$path.ts
  projects/nextjs-appdir/out/lib/ignore/$path.ts
  projects/nextjs-appdir/out/lib/static/$path.ts
  projects/nextjs-src-appdir/src/out/lib/basic/$path.ts
  projects/nextjs-src-appdir/src/out/lib/ignore/$path.ts
  projects/nextjs-src-appdir/src/out/lib/static/$path.ts
  projects/nextjs-src-appdir/src/utils/$path.ts
  src/nextjs/createNextTemplate.ts
  src/nextjs/parseAppDir.ts
Labels: feature

#129 feat: add "or undefined" explicitly to support exactOptionalPropertyTypes
  jest.config.ts
  package.json
  projects/nextjs-appdir/lib/$path.ts
  projects/nextjs-appdir/out/lib/basic/$path.ts
  projects/nextjs-appdir/out/lib/ignore/$path.ts
  projects/nextjs-appdir/out/lib/static/$path.ts
  projects/nextjs-basepath/out/lib/basic/$path.ts
  projects/nextjs-basepath/out/lib/ignore/$path.ts
  projects/nextjs-basepath/out/lib/static/$path.ts
  projects/nextjs-basepath/utils/$path.ts
  projects/nextjs-custom-ext/lib/$path.ts
  projects/nextjs-custom-ext/out/lib/basic/$path.ts
  projects/nextjs-custom-ext/out/lib/ignore/$path.ts
  projects/nextjs-custom-ext/out/lib/static/$path.ts
  projects/nextjs-src/src/out/lib/basic/$path.ts
  projects/nextjs-src/src/out/lib/ignore/$path.ts
  projects/nextjs-src/src/out/lib/static/$path.ts
  projects/nextjs-src/src/utils/$path.ts
  projects/nextjs-stable-appdir/lib/$path.ts
  projects/nextjs-stable-appdir/out/lib/basic/$path.ts
  projects/nextjs-stable-appdir/out/lib/ignore/$path.ts
  projects/nextjs-stable-appdir/out/lib/static/$path.ts
  projects/nextjs/lib/$path.ts
  projects/nextjs/out/lib/basic/$path.ts
  projects/nextjs/out/lib/ignore/$path.ts
  projects/nextjs/out/lib/static/$path.ts
  projects/nuxtjs-basepath/plugins/$path.ts
  projects/nuxtjs-basepath/plugins/util/basic/$path.ts
  projects/nuxtjs-basepath/plugins/util/ignore/$path.ts
  projects/nuxtjs-basepath/plugins/util/static/$path.ts
  projects/nuxtjs-no-slash/plugins/$path.ts
  projects/nuxtjs-no-slash/plugins/util/basic/$path.ts
  projects/nuxtjs-no-slash/plugins/util/ignore/$path.ts
  projects/nuxtjs-no-slash/plugins/util/static/$path.ts
  projects/nuxtjs-src/client/plugins/$path.ts
  projects/nuxtjs-src/client/plugins/util/basic/$path.ts
  projects/nuxtjs-src/client/plugins/util/ignore/$path.ts
  projects/nuxtjs-src/client/plugins/util/static/$path.ts
  projects/nuxtjs/plugins/$path.ts
  projects/nuxtjs/plugins/util/basic/$path.ts
  projects/nuxtjs/plugins/util/ignore/$path.ts
  projects/nuxtjs/plugins/util/static/$path.ts
  src/createNuxtTemplate.ts
  src/getConfig.ts
  src/nextjs/parsePagesDir.ts
  tsconfig.build.json
  tsconfig.json
Labels: documentation, feature, chore
